declare module '@bff' {
    export { server } from '../bff/server'
    export { register } from '../bff/operation/register'
    export { authorize } from '../bff/operation/authorize'
    export { sessions } from '../bff/sessions'
    export { sessionTransform } from '../bff/transformers/session-transform'
    export { addUser } from '../bff/api/add-user'
    export { getUser } from '../bff/api/get-user'
    export { addSession } from '../bff/api/add-session'
    export { deleteSession } from '../bff/api/delete-session'
    export { getSession } from '../bff/api/get-session'
    export { addFavorite } from '../bff/api/add-favorite'
    export { getFavorite } from '../bff/api/get_favorite'
    export { deleteFavorite } from '../bff/api/delete-favorite'
    export { userTransform } from '../bff/transformers/user-transform'
    export { addBookToFavorites } from '../bff/operation/add-book-to-favorites'
    export { removeBookFromFavorites } from '../bff/operation/remove-book-from-favorites'
}
