declare module '@components' {
    export { Button } from '../components/buttons/button'
    export { FormButton } from '../components/buttons/form-button'
    export { Filters } from '../components/filters/filters'
    export { BookCard } from '../components/book-card/book-card'
    export { Icon } from '../components/icon/icon'
    export { IconButton } from '../components/icon-button/icon-button'
    export { Input } from '../components/input/input'
    export { Footer } from '../components/footer/footer'
    export { Header } from '../components/header/header'
    export { Logo } from '../components/header/components/logo/logo'
    export { PasswordInput } from '../components/password-input/password-input'
    export { RecentlyViewed } from '../components/recently-viewed/recently-viewed'
    export { Routes } from '../components/constans/routes'
    export { Search } from '../components/search/search'
}
